.TH "chunk_bounds" 3 "26 Feb 2009" "Version 1.0" "RDWGET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chunk_bounds \- 
.SH SYNOPSIS
.br
.PP
\fC#include <defaults.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long long int \fBstartpos\fP"
.br
.ti -1c
.RI "long long int \fBendpos\fP"
.br
.ti -1c
.RI "size_t \fBmemlen\fP"
.br
.ti -1c
.RI "\fBlnk_http_header\fP * \fBlnk_header\fP"
.br
.ti -1c
.RI "\fBlnk\fP * \fBlnk\fP"
.br
.ti -1c
.RI "\fBfile_fd\fP \fBfd\fP"
.br
.ti -1c
.RI "int \fBmpidx\fP"
.br
.ti -1c
.RI "char * \fBmemory\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 117 of file defaults.h.
.SH "Field Documentation"
.PP 
.SS "long long int \fBchunk_bounds::endpos\fP"
.PP
Definition at line 119 of file defaults.h.
.SS "\fBfile_fd\fP \fBchunk_bounds::fd\fP"
.PP
Definition at line 123 of file defaults.h.
.SS "\fBlnk\fP* \fBchunk_bounds::lnk\fP"
.PP
Definition at line 122 of file defaults.h.
.SS "\fBlnk_http_header\fP* \fBchunk_bounds::lnk_header\fP"
.PP
Definition at line 121 of file defaults.h.
.SS "size_t \fBchunk_bounds::memlen\fP"
.PP
Definition at line 120 of file defaults.h.
.SS "char* \fBchunk_bounds::memory\fP"
.PP
Definition at line 125 of file defaults.h.
.SS "int \fBchunk_bounds::mpidx\fP"
.PP
Definition at line 124 of file defaults.h.
.SS "long long int \fBchunk_bounds::startpos\fP"
.PP
Definition at line 119 of file defaults.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for RDWGET from the source code.
