.TH "downinfo" 3 "26 Feb 2009" "Version 1.0" "RDWGET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
downinfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBresultdir\fP"
.br
.ti -1c
.RI "\fBlnk\fP * \fBlink\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file threadmanager.c.
.SH "Field Documentation"
.PP 
.SS "\fBlnk\fP* \fBdowninfo::link\fP"
.PP
Definition at line 26 of file threadmanager.c.
.SS "const char* \fBdowninfo::resultdir\fP"
.PP
Definition at line 25 of file threadmanager.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for RDWGET from the source code.
