.TH "headerbufs" 3 "26 Feb 2009" "Version 1.0" "RDWGET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
headerbufs \- 
.SH SYNOPSIS
.br
.PP
\fC#include <defaults.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBhdata\fP"
.br
.ti -1c
.RI "size_t \fBhsize\fP"
.br
.ti -1c
.RI "char * \fBremain\fP"
.br
.ti -1c
.RI "size_t \fBrlen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 128 of file defaults.h.
.SH "Field Documentation"
.PP 
.SS "char* \fBheaderbufs::hdata\fP"
.PP
Definition at line 130 of file defaults.h.
.SS "size_t \fBheaderbufs::hsize\fP"
.PP
Definition at line 131 of file defaults.h.
.SS "char* \fBheaderbufs::remain\fP"
.PP
Definition at line 132 of file defaults.h.
.SS "size_t \fBheaderbufs::rlen\fP"
.PP
Definition at line 133 of file defaults.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for RDWGET from the source code.
