.TH "lnk" 3 "26 Feb 2009" "Version 1.0" "RDWGET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lnk \- 
.SH SYNOPSIS
.br
.PP
\fC#include <defaults.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBprotocols\fP \fBprot\fP"
.br
.ti -1c
.RI "char * \fBhostname\fP"
.br
.ti -1c
.RI "char * \fBrquri\fP"
.br
.ti -1c
.RI "char * \fBfilename\fP"
.br
.ti -1c
.RI "int \fBchunknum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 48 of file defaults.h.
.SH "Field Documentation"
.PP 
.SS "int \fBlnk::chunknum\fP"
.PP
Definition at line 54 of file defaults.h.
.SS "char* \fBlnk::filename\fP"
.PP
Definition at line 53 of file defaults.h.
.SS "char* \fBlnk::hostname\fP"
.PP
Definition at line 51 of file defaults.h.
.SS "\fBprotocols\fP \fBlnk::prot\fP"
.PP
Definition at line 50 of file defaults.h.
.SS "char* \fBlnk::rquri\fP"
.PP
Definition at line 52 of file defaults.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for RDWGET from the source code.
