.TH "lnk_http_header" 3 "26 Feb 2009" "Version 1.0" "RDWGET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lnk_http_header \- 
.SH SYNOPSIS
.br
.PP
\fC#include <defaults.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "off_t \fBclen\fP"
.br
.ti -1c
.RI "char * \fBctype\fP"
.br
.ti -1c
.RI "\fBhttp_statcode_grp\fP \fBstatcodegrp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 108 of file defaults.h.
.SH "Field Documentation"
.PP 
.SS "off_t \fBlnk_http_header::clen\fP"
.PP
Definition at line 110 of file defaults.h.
.SS "char* \fBlnk_http_header::ctype\fP"
.PP
Definition at line 111 of file defaults.h.
.SS "\fBhttp_statcode_grp\fP \fBlnk_http_header::statcodegrp\fP"
.PP
Definition at line 112 of file defaults.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for RDWGET from the source code.
