.TH "/home/rado/workspace/rdwget/src/main.c" 3 "26 Feb 2009" "Version 1.0" "RDWGET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/rado/workspace/rdwget/src/main.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <getopt.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <assert.h>\fP
.br
\fC#include 'defaults.h'\fP
.br
\fC#include 'utils.h'\fP
.br
\fC#include 'threadmanager.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBusage\fP (void)"
.br
.ti -1c
.RI "void \fBproc_opts\fP (int argc, char **argv)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char * \fBprgname\fP"
.br
.ti -1c
.RI "char * \fBoptarg\fP"
.br
.ti -1c
.RI "int \fBoptind\fP"
.br
.ti -1c
.RI "int \fBopterr\fP"
.br
.ti -1c
.RI "int \fBoptopt\fP"
.br
.ti -1c
.RI "\fBprgstx\fP \fBprogramsettings\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"
.PP
Definition at line 221 of file main.c.
.SS "void proc_opts (int argc, char ** argv)"
.PP
Definition at line 141 of file main.c.
.SS "void usage (void)"
.PP
Definition at line 117 of file main.c.
.SH "Variable Documentation"
.PP 
.SS "char* \fBoptarg\fP"
.PP
.SS "int \fBopterr\fP"
.PP
.SS "int \fBoptind\fP"
.PP
.SS "int \fBoptopt\fP"
.PP
.SS "char* \fBprgname\fP"
.PP
Definition at line 110 of file main.c.
.SS "\fBprgstx\fP \fBprogramsettings\fP"
.PP
Definition at line 138 of file main.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for RDWGET from the source code.
