.TH "mapitem" 3 "25 Feb 2009" "Version 1.0" "RDWGET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mapitem \- 
.SH SYNOPSIS
.br
.PP
\fC#include <defaults.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBmemory\fP"
.br
.ti -1c
.RI "long long int \fBmemlen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 95 of file defaults.h.
.SH "Field Documentation"
.PP 
.SS "long long int \fBmapitem::memlen\fP"
.PP
Definition at line 98 of file defaults.h.
.SS "char* \fBmapitem::memory\fP"
.PP
Definition at line 97 of file defaults.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for RDWGET from the source code.
