.TH "prgstx" 3 "26 Feb 2009" "Version 1.0" "RDWGET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prgstx \- 
.SH SYNOPSIS
.br
.PP
\fC#include <defaults.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBchunks\fP"
.br
.ti -1c
.RI "const char * \fBresultdir\fP"
.br
.ti -1c
.RI "int \fBnumlinks\fP"
.br
.ti -1c
.RI "char ** \fBlinks\fP"
.br
.ti -1c
.RI "int \fBipv6\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file defaults.h.
.SH "Field Documentation"
.PP 
.SS "int \fBprgstx::chunks\fP"
.PP
Definition at line 40 of file defaults.h.
.SS "int \fBprgstx::ipv6\fP"
.PP
Definition at line 45 of file defaults.h.
.SS "char** \fBprgstx::links\fP"
.PP
Definition at line 44 of file defaults.h.
.SS "int \fBprgstx::numlinks\fP"
.PP
Definition at line 43 of file defaults.h.
.SS "const char* \fBprgstx::resultdir\fP"
.PP
Definition at line 41 of file defaults.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for RDWGET from the source code.
