.TH "/home/rado/workspace/rdwget/src/utils.h" 3 "26 Feb 2009" "Version 1.0" "RDWGET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/rado/workspace/rdwget/src/utils.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'defaults.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBlength\fP(X)   sizeof (X) / sizeof (X[0])"
.br
.RI "\fICalculates length of array. \fP"
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define length(X)   sizeof (X) / sizeof (X[0])"
.PP
Calculates length of array. 
.PP
(defined as size of array / size of first item of array 
.PP
Definition at line 10 of file utils.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for RDWGET from the source code.
